Add affinity and tolerations
munnerz/kube-plex pull request #75
Opened 2020-01-02 23:19 UTC by casidiablo

This is useful when running on clusters with more than one worker where one would like to pin plex to a specific node.

2020-01-04 19:57 UTC, onedr0p commented
@zee-ahmed or @munnerz this would be nice to have. Any chance of a merge?

2020-01-04 19:59 UTC, zee-ahmed commented
> @zee-ahmed or @munnerz this would be nice to have. Any chance of a merge?

Yep! I can see the value in this. Will start the review process. Thanks!

2020-01-04 20:03 UTC, simplyzee requested changes
Thanks @casidiablo for the PR. I can see how useful this is with plex. 

Would you be able to add some documentation to the chart regarding affinity rules and the values.yaml?

2020-01-08 07:27 UTC, casidiablo commented
Done. Made the changes inline through Github so please make sure to squash the commits while merging.

2020-01-08 13:49 UTC, onedr0p commented
Looks good to me, @zee-ahmed ship it :)

2020-01-08 13:52 UTC, merged

2020-01-08 13:52 UTC, zee-ahmed commented
Merged! thanks, @casidiablo and @onedr0p :smile: